### ISSUE TITLE
Version 0.13.0 not found

### ISSUE THREAD

**Issue by sleith** [OneSignal/OneSignal-Gradle-Plugin#157]
Hi,
Seems the new version 0.13.0 is not published to plugins.gradle.org yet. 
https://plugins.gradle.org/plugin/com.onesignal.androidsdk.onesignal-gradle-plugin shows latest is 0.12.10.

Please help. Thanks

**Comment by jkasten2** [comment]
@sleith Thanks for reporting! We have resolved the issue with a 0.13.2 release. For more details on why 0.13.0 and 0.13.1 isn't available see PR #160.

One caveat is that you have to use an exact version of 0.13.2 to get this version. Version ranges won't pick up this version yet due the fact that the Gradle Plugin Portal hasn't update the [OneSignal maven-metadata.xml](https://plugins.gradle.org/m2/gradle/plugin/com/onesignal/onesignal-gradle-plugin/maven-metadata.xml) to include 0.13.2. However I would assume this will be fixed in the next day or so.
