### ISSUE TITLE
Question about not using the plugin

### ISSUE THREAD

**Issue by cmargonis** [OneSignal/OneSignal-Gradle-Plugin#179]
Hello folks 👋 ,

I'd like to ask about the necessity of this plugin. Given our team uses Firebase BOM that ensures Firebase libraries work well together, we're thinking of removing the One Signal gradle plugin, so as to improve build times.

Any thoughts on this? Will we have to pay attention to anything other than just testing our OneSignal push notifications with each update?

Thanks!

**Comment by jkasten2** [comment]
Hey @cmargonis 👋 , thats a good question. This Gradle plugin is recommend but isn't required for the [OneSignal-Android-SDK](https://github.com/OneSignal/OneSignal-Android-SDK) to work correctly.

This plugin currently only checks and fix dependencies that are too low or too high to prevent build or runtime issues. As you noted since you are using the Firebase BOM to define you dependencies the chances of conflicts are lower. If your project is a native one any `build.gradle` changes you have to make will be straightforward if you have to upgrade anything. This plugin is more useful to save time on setting up OneSignal without have to make manual changes, this is especially helpful to  new Android developers or one that use a framework like React Native or Flutter.
